ManyToOneRelations/urls.py
from django.contrib import admin
from django.urls import path
from WebApp import views

urlpatterns = [
    path('', views.teamslist),
    path('admin/', admin.site.urls),
]

WebApp/models.py
from django.db import models

class Team(models.Model):
    tname = models.CharField(max_length=255)

    def __str__(self):
        return self.tname

class Player(models.Model):
    pname = models.CharField(max_length=255, primary_key=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, )

    def __str__(self):
        return self.pname

WebApp/views.py
from django.shortcuts import render
from .models import Team

def teamslist(request):
    items = Team.objects.all()
    return render(request, 'TeamPlayer.html', {'items':items})

templates/Base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>


    <div class="container mt-2">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

templates/TeamPlayer.html
{% extends 'Base.html' %}

{% block title %}TEAMPLAYER{% endblock %}

{% block content %}

<div>
    {% for instance in items %}
        <h2>{{ instance.tname }}</h2>
        {% for player in instance.player_set.all %}
        <h4>{{ player.pname }}</h4>
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}